### ISSUE TITLE
Can we display some general observing/sky conditions?  If so, where do we get the information?

### ISSUE THREAD

**Issue by dyerlytle** [LowellObservatory/NightWatch#10]

**Comment by astrobokonon** [comment]
~~I *think* this is probably a very wide topic that we don't have the tools to narrow into something workable yet.~~  We can get a decent measure of sky brightness from the guide statistics mentioned in issue #6 but the other two mentioned in the original title are quagmires to actually measure well so I've made the title far more general.

Some bulk assessment could be measured and plotted using the existing allsky camera images as the source, but since the moon saturates it's hard to say what is needed.  It could turn out that to get reliable numbers, we'd need to both work on the raw FITS files as well as alter the allsky image acquisition sequence that @loxlig maintains.

At the [3.5m at Apache Point Obs. in NM](https://irsc.apo.nmsu.edu/irsc_doc/), they do an interesting thing where they mask out the horizon objects from their all sky images and then calculate statistics on the whole image remaining.  There might be enough unsaturated pixels even with the full moon that this is good enough and interesting as a statistic so I'll do that with the rest the afternoon and report back.

**Comment by astrobokonon** [comment]
By working on the absolute value of differential image pairs, the Moon problem can be mitigated with the images we have right now.  

That makes the median value of the sky pretty close to zero on a clear night, and since the moon is saturated it makes it act as a self-mask.  The moon has a little bit of slop on either side due to actual lunar motion in the sky but it's surprisingly good.  

The standard deviation actually becomes a decent measure of the sky at that point, and seems to be tracking actual cloud passes.  Pretty sure the sharp spikes are mostly telescope movements, which cause glints of the telescope structure in the moon light.  Better masking of the structure should remove them.  The chunky peak at around X=525 is coincident with a period of clouds passing in front of the full moon.

![figure_1](https://user-images.githubusercontent.com/1168555/47596238-bfdb8c80-d939-11e8-82ed-63bb94adf50a.png)

(note: the Y axis on the plots is in AllSkyCam's ADU/sec)

![simg_0530](https://user-images.githubusercontent.com/1168555/47596637-6aed4580-d93c-11e8-993f-ca5492bf49e8.png)

**Comment by astrobokonon** [comment]
Ok, this time with "better" masking and labeling.  Better is in quotes because I took like 30 seconds to freehand add bits to the mask in GIMP, but it's WAAAAY cleaner already. I am pretty amazed how well this worked out and thought I was just going to play around with it for the rest of this Friday afternoon.

![simg_0530](https://user-images.githubusercontent.com/1168555/47596886-8bb69a80-d93e-11e8-84b6-32827a95c449.png)

stddev (red) is *much* cleaner now that I cut out the enclosure and the trees; also added the sky average (green) too so you can see how that is trending:

![figure_1](https://user-images.githubusercontent.com/1168555/47597019-d4bb1e80-d93f-11e8-9c74-0a9dbd3e7bee.png)

**Comment by astrobokonon** [comment]
@LowellObservatory/nightops it would be good to get some feedback on this issue (reminder that the link to what I'm referencing will be towards the bottom of the notification email).

I can run this on archival data and probably should, but it would be good to get feedback early before that happens.

**Comment by dyerlytle** [comment]
I was talking to Nick about using the all sky camera dataset for projects with the Software Syndicate.  Initially, I talked about looking at transient events and trying to get a list of meteors every night.  He brought up the idea of using the stars in the field to make a real time extinction map of the sky to help astronomers adjust their observing pattern to take advantage of the best seeing/least extinction.  Perhaps this could be a feature we could eventually add to NightWatch once we figure out how to do it and how well it works.

**Comment by astrobokonon** [comment]
Closed in favor of tracking this over at https://github.com/LowellObservatory/Camelot/issues/9
