### ISSUE TITLE
What sort of user authentication should be use to implement security for the website?  How is that implemented in Django?

### ISSUE THREAD

**Issue by dyerlytle** [LowellObservatory/NightWatch#12]

**Comment by charlesvbw** [comment]
I like .htaccess because it's easy to manage and implement, but there are plenty of plugins available to authenticate users (possibly to AD which would be preferable)

**Comment by astrobokonon** [comment]
I'm going to close this because for now, I think being behind the firewall is sufficient.  If it grows in audience (public/outreach or whatever), then we can of course revisit.

For the next project, (involving the instrument coolers) user authentication/roles will probably be required, so I'll defer this until that project actually starts.
