### ISSUE TITLE
Determine where we will get information for Warnings or Alerts and how that info will be displayed.

### ISSUE THREAD

**Issue by dyerlytle** [LowellObservatory/NightWatch#8]

**Comment by astrobokonon** [comment]
To add more context before we all forget - this came up in the context of the LabVIEW issued warnings and alerts that the current DOL is able to get access to but (currently) aren't pushed out onto the broker or anywhere else.  

An intermediate solution might be to have the current DOL stripped down to brass tacks and only collect and publish these alerts, or to have those alerts written to a file for consumption elsewhere somehow.  TBD and it depends on some LabVIEW work.

A separate but obviously related issue is to collect and highlight *other* operational alerts, such as the DeVeny (or any, really) calibration lamps being left on for a long time or instrument temperatures being out of spec.  These are currently handled by shell scripts, mostly, but there's a bunch of ways to do these since the source data is usually way more available.

**Comment by hlars-freehub** [comment]
DOL doesn't get the kind of alerts that would be useful to astronomers. You want things pushed by TCS-- wrap limit & keyhole warnings. The dome occultation warning would be pushed by DCS.

**Comment by astrobokonon** [comment]
I'm forcing further discussion to move over to #31 where it'd be more focused.  Please go there!
